name: sticker_counter
description: "Sticker Counter - Track your habits with custom sticker buttons"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: ^1.0.7
  image: ^4.1.7
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.9.0
  fl_chart: ^0.66.2
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  intl: ^0.19.0
  uuid: ^4.3.3
  image_cropper: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
